### ISSUE TITLE
Update to nbt-js release, replacing custom fork

### ISSUE THREAD

**Issue by deathcap** [deathcap/playerdat#2]
Now that a new version of https://github.com/sjmulder/nbt-js/issues/10 is on NPM, update this module to use it instead of my branch

**Comment by deathcap** [comment]
playerdat unit tests succeed with nbt@0.4.0, but that doesn't have https://github.com/sjmulder/nbt-js/pull/11 update dependencies, and nbt@0.5.0  playerdat npm test fails with:

```
TAP version 13
# basic
Inventory { array: [ , , , , , , , , ,  ], width: 10, height: 1 }
not ok 1 should be equal
  ---
    operator: equal
    expected: 9
    actual:   10
  ...
ok 2 should be equal
[stdin]:14308
    t.equal(inventory.get(0).toString(), '1:pickaxeWood');
                            ^

TypeError: Cannot read property 'toString' of undefined
    at [stdin]:14308:29
    at [stdin]:14280:7
    at [stdin]:6197:6
    at Gunzip.onEnd ([stdin]:953:5)
    at Gunzip.EventEmitter.emit ([stdin]:5151:20)
    at Array.<anonymous> ([stdin]:2374:16)
    at drainQueue ([stdin]:11989:28)
    at Timer.listOnTimeout (timers.js:92:15)
npm ERR! Test failed.  See above for more details.
```

playerdat npm test with nbt@0.6.0 fails earlier:

```
TAP version 13
# basic
Inventory { array: [ , , , , , , , , ,  ], width: 10, height: 1 }
not ok 1 should be equal
  ---
    operator: equal
    expected: 9
    actual:   10
  ...
ok 2 should be equal
[stdin]:14308
    t.equal(inventory.get(0).toString(), '1:pickaxeWood');
                            ^

TypeError: Cannot read property 'toString' of undefined
    at [stdin]:14308:29
    at [stdin]:14280:7
    at [stdin]:6197:6
    at Gunzip.onEnd ([stdin]:953:5)
    at Gunzip.EventEmitter.emit ([stdin]:5151:20)
    at Array.<anonymous> ([stdin]:2374:16)
    at drainQueue ([stdin]:11989:28)
    at Timer.listOnTimeout (timers.js:92:15)
npm ERR! Test failed.  See above for more details.
```

**Comment by deathcap** [comment]
No longer seeing the "npm ERR! invalid: readable-stream" errors from npm list on node 5.3.0 (previously seen on node 0.12, prompting the dependency updates), so nbt 0.4.0 should be sufficient for now. New issue for updating to a newer release: https://github.com/deathcap/playerdat/issues/3
